server:
  port: 1111
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      username: nacos
      password: nacos
    gateway:
      routes:
        - id: product
          uri: lb://product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        - id: consumer
          uri: lb://consumer
          predicates:
            - Path=/api/consumer/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}