server:
  port: 9999
spring:
  application:
    name: product
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      username: nacos
      password: nacos
  config:
    import:
      - optional:nacos:nacos-config.yaml